services:
  - type: web
    name: cv-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: DATABASE_URL
        fromGroup: cv-db-creds